coordinator=true
node-scheduler.include-coordinator=true
http-server.http.port=80
discovery.uri=http://localhost:80
http-server.process-forwarded=true
http-server.authentication.type=PASSWORD
internal-communication.shared-secret=IY6EBXHZRRQsjSsFT5fmwrBZzTHLWb/Rv4kFP1