- name: Install ufw
  ansible.builtin.dnf:
    name:
      - ufw
    state: latest
  become: true
  become_user: root
- name: enable ufw
  ansible.builtin.shell: "echo y | ufw enable"
  become: true
  become_user: root
- name: allow traffic from cluster hosts
  ansible.builtin.shell: "ufw allow from {{ item }}"
  loop: "{{ query('inventory_hostnames', 'all')  }}"
  become: true
  become_user: root