apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  template:
    spec:
      containers:
      - name: hello
        image: ubuntu:latest
        command: ["echo", "Hello, world"]
      restartPolicy: Never
  backoffLimit: 4
