apiVersion: batch/v1
kind: Job
metadata:
  name: mnist-replica
spec:
  completions: 20
  parallelism: 3 
  template:
    metadata:
      labels:
        app: mnist-replica
    spec:
      topologySpreadConstraints:
      - maxSkew: 1
        topologyKey: kubernetes.io/hostname
        whenUnsatisfiable: DoNotSchedule
        labelSelector:
          matchLabels:
            app: mnist-replica
    spec:
      containers:
      - name: mnist
        image: uccaoke-reg.comp0235.condenser.arc.ucl.ac.uk/class/python_mnist:latest
      resources:
        limits:
          cpu: "2"
          memory: "3.5Gi"
        requests: 
          cpu: "1"
          memory: "2Gi"  
      restartPolicy: Never
  backoffLimit: 4
